### ISSUE TITLE
Latest version is retired

### ISSUE THREAD

**Issue by APB9785** [ueberauth/ueberauth#196] opened 2024-01-03 16:45 UTC
### Steps to Reproduce

Use mix deps.get to install the most recent version of Ueberauth

### Expected Result

Latest version works properly without breakage

### Actual Result

Receive warning that the installed version is retired

**Comment by yordis** [comment] 2024-01-03 17:43
Right, wouldn't this be a Hex problem thou? The version is correctly marked as retired in hex. So, I am not sure what to do other than make up a version to, at the very least, avoid the retired version to be the latest one.

**Comment by APB9785** [comment] 2024-01-03 17:57
I think this is a good fit for a patch release i.e. 0.10.7

**Comment by yordis** [comment] 2024-01-03 20:41
Right, but there are no changes currently made to be released. Sorry for repeating again, but this feels a Hex problem more than anything.

If I release something, then rollback those ver changes, and mark the release as depricated; I shouldn't have to "made up" changes in order to release something.

No?

Please help me to understand the flaws in my reasoning 🙏🏻

**Comment by APB9785** [comment] 2024-01-04 00:48
The flaw in reasoning is the word "rollback" - hexpm is immutable and git versioning only goes forwards.  So when you think in terms of a "rollback" it is already incorrect.  In order to revert "change A", you must release a new patch which applies "change B" - where A/B have an inverse relationship.

**Comment by yordis** [comment] 2024-01-04 01:41
My apologies, I rollback on GitHub the changes, not in Hex.

The point is, why is Hex recommending a version marked as "deprecated" without, at the very least, a warning about it?

**Comment by APB9785** [comment] 2024-01-04 02:09
They do provide a warning, that's what alerted me to the issue in the first place 🙂 

Seems like the "retire/deprecate" feature works well in these cases:
* the retired version is a previous one, and there is a more recent version for users to upgrade
* the retired version is the most recent one, because the library has been abandoned/archived

But not so well in this case here:
* the retired version is the most recent one, but the library is still actively maintained

**Comment by yordis** [comment] 2024-01-04 02:13
Then it sounds that works as intended thou. They are no new changes to release.

**Closed by yordis** 2024-01-04 02:13 UTC
